### ISSUE TITLE
给大佬加个需求：自定义pageSizes、pageIndex、 pageSize；tks~

### ISSUE THREAD

**Issue by fjgy99** [TanxiangCode/elt-transfer#19]

**Comment by TanxiangCode** [comment]
我懒。。要不你fork一份？

**Comment by fjgy99** [comment]
哈哈，我原本也是想偷个懒，直接install后用大佬的就行。既然大佬都发话了，那我就不客气把你代码都clone下来改吧改吧变成自己的了哟~

**Comment by davis1214** [comment]
已经 fork 一份，并做了调整，放到自己 Repository [elt-transfer](https://github.com/davis1214/elt-transfer)
