### ISSUE TITLE
请问左侧的初始数据支持异步获取吗？

### ISSUE THREAD

**Issue by coderzym** [TanxiangCode/elt-transfer#25]
请问左侧的初始数据支持异步获取吗？我获取并赋值，左侧的列表也没有刷新

**Comment by coderzym** [comment]
没事了，我自己最后又封了一下，支持了

**Comment by Ru1n33** [comment]
请问怎么处理的啊大佬

**Comment by TanxiangCode** [comment]
写得不够明显？？
![image](https://user-images.githubusercontent.com/42427662/190541171-898ea3d6-d26f-4ec3-bdfc-1c5fa08fda53.png)

**Comment by Ru1n33** [comment]
初始化的时候渲染数据没问题，但是如果需要通过接口异步渲染，就无法渲染了，这个怎么处理呢？

**Comment by TanxiangCode** [comment]
提供一下你写的代码Demo我看看才知道是什么情况

**Comment by Ru1n33** [comment]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/41810858/190543026-5b4e850b-84fa-401b-943f-41210c443b93.png">
<img width="814" alt="image" src="https://user-images.githubusercontent.com/41810858/190543063-3d77c622-c51d-4c61-9bc8-d18dcf3862f2.png">
就是说，我一开始穿梭框没有数据，我需要根据传的一个id来调用接口异步获取数据并渲染，但是发现没有触发这个分页的call back

**Comment by TanxiangCode** [comment]
首先，这个组件在create的时候是会默认触发paginationCallBack这个回调的，所以它肯定会在初始化时回调一次。
其次。如果你想在点击确定的时候传递一个acctId，那么你应该在data中定义一个变量，用于存储你弹窗获取的到的ID，并在paginationCallBackMoust中使用。
最后，你不应该手动调用paginationCallBackMoust，这样调用了，组件内部怎么接收得到你请求的数据？你应该使用ref调用组件内部的onLeftQuerySubmit方法

**Comment by Ru1n33** [comment]
ok，我去试试，感谢大佬解答

**Comment by Ru1n33** [comment]
可以了，感谢大佬，之前去ref调用组件的callback方法结果报错了，onLeftQuerySubmit方法可以正常渲染了
