### ISSUE TITLE
使用控件发生的一些问题。

### ISSUE THREAD

**Issue by 1228181394** [TanxiangCode/elt-transfer#37]
1.右侧数据无法回显。
2.右侧点击筛选后再点击保存能够保存成功，但是监听回显后的数据都被清空。发现是值未被清空。
this.$refs.eltTransfer.rightConditionTemp.name = '';//右侧点击筛选后，保存数据不显示问题
this.$refs.eltTransfer.rightQueryCondition.name = '';//右侧点击筛选后，保存数据不显示问题

**Comment by TanxiangCode** [comment]
麻烦提供一个简易的demo

**Comment by 1228181394** [comment]
已解决是写的弹窗问题导致。
