### ISSUE TITLE
左侧的查询筛选功能失效，右侧的正常

### ISSUE THREAD

**Issue by SaberInoryKiss** [TanxiangCode/elt-transfer#6]

**Comment by TanxiangCode** [comment]
左侧的筛选，因为在设计上是需要去请求服务端接口的，所以需要使用Promise返回结果，具体你可以看下例子[examples](https://github.com/TanxiangCode/elt-transfer/blob/master/examples/App.vue)

**Comment by SaberInoryKiss** [comment]
> 左侧的筛选，因为在设计上是需要去请求服务端接口的，所以需要使用Promise返回结果，具体你可以看下例子[examples](https://github.com/TanxiangCode/elt-transfer/blob/master/examples/App.vue)

好的，谢谢哈
